# Generated by Django 5.1.4 on 2025-01-10 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Оценка не должна быть ниже 0'), django.core.validators.MaxValueValidator(6, 'Оценка не должна превышать 5')], verbose_name='Рейтинг'),
        ),
    ]
