# Generated by Django 5.1.4 on 2025-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers_prod',
            name='price',
            field=models.IntegerField(default=123, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
