# Generated by Django 5.1.4 on 2025-01-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sellers_prod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='city',
            field=models.CharField(default=123, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
