# Generated by Django 5.1.4 on 2025-01-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sellers_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='log_img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Логотип'),
        ),
    ]
