# Generated by Django 5.1.4 on 2025-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
