# Generated by Django 5.1.4 on 2025-01-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название категории характеристики')),
            ],
            options={
                'verbose_name': 'Категория характеристики',
                'verbose_name_plural': 'Категории характеристик',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название характеристики')),
                ('spec_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.spec_category', verbose_name='Категория характеристики')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory', verbose_name='Подкатегория товара')),
            ],
            options={
                'verbose_name': 'Характеристики',
                'verbose_name_plural': 'Характеристик',
            },
        ),
        migrations.CreateModel(
            name='Spec_vals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(verbose_name='Значение')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.specification', verbose_name='Характеристика продукта')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
