# Generated by Django 5.1.4 on 2025-12-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_spec_category_specification_spec_vals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spec_vals',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товаров'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Все характеристики'},
        ),
    ]
